### ISSUE TITLE
golang-cross build images should contain all needed build components for beats

### ISSUE THREAD

**Issue by mikemadden42** [elastic/golang-crossbuild#23] opened 2019-04-25 19:55 UTC
We ran into an [issue](https://internal-ci.elastic.co/job/elastic+release-manager+release-staging/129/console) where we could not install `libsystemd-dev:i386` which is needed to cross compile journalbeat.  It would be nice if this package & its requirements were included in the golang-crossbuild images.

```
08:12:56 E: Unable to correct problems, you have held broken packages.
08:12:56 Error: running "apt-get install -y --no-install-recommends libsystemd-dev:i386" failed with exit code 100
08:12:56 Error: failed building for linux/386: exit status 100
08:12:56 failed building for linux/386: exit status 100
08:12:56 E: Unable to correct problems, you have held broken packages.
08:12:56 Error: running "apt-get install -y --no-install-recommends libsystemd-dev:i386" failed with exit code 100
08:12:56 Error: failed building for linux/386: exit status 100
08:12:56 failed building for linux/386: exit status 100
```

**Comment by andrewkroh** [comment] 2019-04-25 21:16
I agree. I was coming to open the same issue and found this.

Originally I opted for having this project be generic and only have the core dependencies necessary for running a cross-compiler. But this restriction causes too many problems when the upstream package repos change / go offline / or are retired so embedding the Debian packages necessary for Beats will help and will make builds more reproducible.

**Comment by mikemadden42** [comment] 2020-01-27 18:45
Initial PR for `x-pack/auditbeat` updates is available (https://github.com/elastic/golang-crossbuild/pull/39).

**Comment by v1v** [comment] 2020-07-20 13:29
I'll close this issue since it was done but the `zube` bot decided to reopen it :(

**Closed by v1v** 2020-07-20 13:29 UTC
Labels: Team:Automation, [zube]: Ready, automation, bug
